name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3

      - name: Build for ${{ matrix.os }}-${{ matrix.arch }}
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -ldflags="-X 'main.Version=${{ github.ref_name }}'" -o bin/s3backup-${{ matrix.os }}-${{ matrix.arch }} .

      - name: Save binaries artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bin
          path: bin/*

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [worker.oci]
              max-parallelism = 4
      - name: Log in to registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u alexandretrichot --password-stdin
      - name: Build and Push
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --build-arg VERSION=${{ github.ref_name }} \
          --tag alexandretrichot/s3backup:${{ github.ref_name }} \
          --tag alexandretrichot/s3backup:latest \
          --push \
          --file Dockerfile .

  release:
    needs: [build, docker]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - run: tree

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: bin/*
